"""Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibo_num(n=-1,f1=1,f2=2,nmax=-1):  # Generate fibonacci numbers upto n terms or nmax value 
	l=[f1,f2]
	if (n>2):
		for i in range(n-2):
			l.append(l[-1]+l[-2])
	elif(nmax>0):
		while(l[-1]<nmax):
			l.append(l[-1]+l[-2])
		l=l[:-1]
	return l

fibo_list = fibo_num(nmax = 4000000)
ans = sum(i for i in fibo_list if i%2==0)
print(ans)